name: Update tennis matches CSV

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

permissions:
  contents: write

jobs:
  update-wta:
    name: Update WTA CSV
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pypdf urllib3 beautifulsoup4

      - name: Run WTA parser
        run: |
          python run_tennis_parser.py \
            --tour wta \
            --output "data/wta_matches_format.csv" \
            --pdf-url "https://wtafiles.wtatennis.com/pdf/draws/2026/902/MDS.pdf"

      - name: Commit WTA CSV if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add data/wta_matches_format.csv

          if git diff --cached --quiet; then
            echo "Nessuna modifica da committare per WTA"
          else
            git commit -m "Update WTA matches CSV"
            git push
          fi

  update-atp:
    name: Update ATP CSV
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pypdf urllib3 beautifulsoup4

      - name: Run ATP parser
        run: |
          python run_tennis_parser.py \
            --tour atp \
            --output "data/atp_matches_format.csv" \
            --tournament-url "https://www.atptour.com/en/scores/current/indian-wells/404/" \
            --draw-page "https://www.atptour.com/en/scores/current/indian-wells/404/draws" \
            --results-page "https://www.atptour.com/en/scores/current/indian-wells/404/results" \
            --tournament-id "404" \
            --year "2026"

      - name: Commit ATP CSV if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add data/atp_matches_format.csv

          if git diff --cached --quiet; then
            echo "Nessuna modifica da committare per ATP"
          else
            git commit -m "Update ATP matches CSV"
            git push
          fi
